### ISSUE TITLE
1.36 "Have not received response from pool" error

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#212] opened 2022-01-08 07:38 UTC
I am using -t 80, but somehow this happened:
![image](https://user-images.githubusercontent.com/81028826/148636040-5f1f57ad-7b21-4809-8f25-21b51ca10b2c.png)

And then invalid shares started showing up:
![image](https://user-images.githubusercontent.com/81028826/148636105-0898b2d3-cdb1-43f2-b26d-d2011ee347f1.png)
![image](https://user-images.githubusercontent.com/81028826/148636141-2383ccc1-82fa-4539-9e11-c318266adf2b.png)

**Comment by MrNuTruT** [comment] 2022-01-08 08:28
I have the same on 1.36 hiveos

**Comment by sp-hash** [comment] 2022-01-08 09:57
Is this only happening on crazypool?

**Comment by MrNuTruT** [comment] 2022-01-08 10:20
2miners with hiveos

**Comment by hintro32** [comment] 2022-01-08 10:28
Also I think when this happened, the last job sent by pool was less than 60 seconds ago, plus there was a solution accepted.

**Comment by sp-hash** [comment] 2022-01-08 11:33
I managed to reproduce by unplugging the ethernet cable, and replug it. Did some small changes to the code, and not able to reproduce anymore.. Invalid shares. Will test some more then close. Fixed in 1.37

**Comment by MrNuTruT** [comment] 2022-01-08 21:23
don't work

![image](https://user-images.githubusercontent.com/11719145/148660419-b846be5f-038c-461d-b3c5-20fa30079ca5.png)

**Comment by hintro32** [comment] 2022-01-08 23:38
I reproduced it with -t 30 in 1.37:
![image](https://user-images.githubusercontent.com/81028826/148663567-01257e4c-9acd-41d0-9269-fd4ec3a1955b.png)
![image](https://user-images.githubusercontent.com/81028826/148663578-9b98556c-a1d7-42e7-8a06-d36da73d685b.png)

**Comment by sp-hash** [comment] 2022-01-10 23:29
fixed in v1.38

**Closed by sp-hash** 2022-01-10 23:29 UTC
