### ISSUE TITLE
Version 1.25 more rejected shares for AMD cards

### ISSUE THREAD

**Issue by TunayCVS** [sp-hash/TeamBlackMiner#139] opened 2021-11-17 18:35 UTC
Version 1.24 makes rejected shares for AMD cards on hiveon pool, version 1.25 makes more rejected shares on hiveon pool. "Default xintensity on hiveon and binance changed to 24 to reduce stales (AMD)"          -----> ???

**Comment by sp-hash** [comment] 2021-11-17 18:54
Which amd cards do you use? Can you take a screenshot of the miner? Rejected shares have a message (why they get rejected.) can you check what kind of rejects in the logfiles?

**Comment by TunayCVS** [comment] 2021-11-17 19:03
I'm mining on Hiveos with AMD XFX 6600XT, XFX 6700XT cards. I don't get any errors, on the Hiveos screen, for example, A1 starts from R1 and the number of rejected shares increases faster than the previous version, moreover, there is no error record. In addition, although I write the cards I want to cancel (for example, "0,1") in the "Disable cards" function on the flight sheet screen, it still continues to mining with those cards, so that function does not work either.

**Comment by sp-hash** [comment] 2021-11-17 19:31
Can you ssh into the rig? We need to see what kind for rejected shares you get in the miner window

**Comment by TunayCVS** [comment] 2021-11-17 19:47
> Can you ssh into the rig? We need to see what kind for rejected shares you get in the miner window

I'll take a screenshot as soon as possible, thanks.

**Comment by sp-hash** [comment] 2021-11-17 19:47
![duplicate](https://user-images.githubusercontent.com/9572668/142271841-b16f84d5-ad30-4fce-9f57-271101e8fb98.png)

I managed to reproduce now on one of my rigs. is this the rejects you are seeing?

**Comment by TunayCVS** [comment] 2021-11-17 19:50
This is exactly what the error looks like

**Comment by sp-hash** [comment] 2021-11-17 19:52
ok. Looks like a bug. Other pools doesn't have this. We will investigate

**Comment by TunayCVS** [comment] 2021-11-17 19:54
Thank you very much for your interest, I wish you success.

**Comment by sp-hash** [comment] 2021-11-17 20:35
Fixed the duplicate bug in v1.26. the timeout on the 1660ti could be related, so please test if it's fixed in the next release

**Closed by sp-hash** 2021-11-17 20:35 UTC

**Comment by sp-hash** [comment] 2021-11-27 18:01
We fixed another bug that reduce the rejected shares on this pool. v1.28
