### ISSUE TITLE
Ethermine Reported Hashrate is null

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#44] opened 2021-10-01 09:45 UTC
Hello,

![image](https://user-images.githubusercontent.com/11719145/135600120-2eb65db7-9159-4d53-badb-9fc9e87eb8bd.png)

Version 1.10 not fix the reported hashrate on ethermine !

thank you

**Comment by sp-hash** [comment] 2021-10-01 09:51
ssl is not working. Are you connection with the bminer_ethermine_eth.bat script? I get stats with this script

**Comment by MrNuTruT** [comment] 2021-10-01 10:22
yes i run tbminer_ethermine_eth.bat script ! what should I do ?

**Comment by MrNuTruT** [comment] 2021-10-01 10:23
![image](https://user-images.githubusercontent.com/11719145/135604842-41422021-f451-45a1-885b-e542527f9d28.png)
the current hashrate is ok

**Comment by boucz** [comment] 2021-10-01 19:35
strangely, if I replace %computername% in the .bat file with the name of the worker, I have the reported hashrate working :)

**Comment by MrNuTruT** [comment] 2021-10-04 17:27
![image](https://user-images.githubusercontent.com/11719145/135896710-235faa73-f34d-46c4-a638-3309268286b2.png)
same thing with 1.11

**Comment by binaryf** [comment] 2021-10-07 04:54
Sorry about that. We are reporting the hashrate in intervals of 1 minute.
I am unable to reproduce the problem.

**Comment by binaryf** [comment] 2021-10-08 06:39
I am sure you have the worker-name right.
I will browse through the sourcecode to try to see if there could be any exception.

**Comment by sp-hash** [comment] 2021-10-15 13:08
fixed in v1.15

**Closed by sp-hash** 2021-10-15 13:08 UTC

**Comment by sp-hash** [comment] 2021-10-15 16:38
v1.15 has been released. Please retest if you have time. thanks.

**Comment by MrNuTruT** [comment] 2021-10-17 14:20
in v1.15 same thing
![image](https://user-images.githubusercontent.com/11719145/137631467-b65a0ab0-cada-462e-a9bd-877ce317cb64.png)

**Comment by MrNuTruT** [comment] 2021-10-19 18:35
![image](https://user-images.githubusercontent.com/11719145/137970421-ae8fcce1-94c4-4dc0-8a5b-52199f2e9dfe.png)
in 1.17

**Comment by sp-hash** [comment] 2021-10-19 18:47
Use another workernane when you change the miner. 
PCGODZILLA? and wait more than 5 mins

**Comment by sp-hash** [comment] 2021-10-21 21:45
fixed in v1.18. Problem with uppercase workers
