### ISSUE TITLE
Miner won't start on hiveos 

### ISSUE THREAD

**Issue by SirSchulz** [sp-hash/TeamBlackMiner#215] opened 2022-01-12 05:40 UTC
I have tested every version from v1. 2 - v1. 35
![Screenshot_20220111-233409_Chrome](https://user-images.githubusercontent.com/97582034/149070407-071e5e01-01d2-4268-a4c4-429ab26fd083.jpg)

**Comment by sp-hash** [comment] 2022-01-12 09:07
Try to run without -b (amd-only) option.

**Comment by SirSchulz** [comment] 2022-01-12 09:08
Already tried. Not working

**Comment by sp-hash** [comment] 2022-01-12 09:13
Does one card work -Y [1] ?

**Comment by SirSchulz** [comment] 2022-01-12 09:28
Ok I tested it with 0 1 2 3 every card works alone except number 2

**Comment by sp-hash** [comment] 2022-01-12 09:34
Good.
You can try with -K 1 (dagintensity)

Perhaps the clocks are too high for this card. Review the OC settings.

**Comment by SirSchulz** [comment] 2022-01-12 09:36
With trm everything works great. I will try it with dag intensity

**Comment by sp-hash** [comment] 2022-01-12 09:38
The problem is probobly that TBM isn't applying the same memtweak setting as TRM. 
TBM is slow on the Vegas, and we haven't solved it yet.

**Comment by SirSchulz** [comment] 2022-01-12 11:04
So I have tested with dag intensity and no oc settings still the same problem with card 2
Card 2 is a RX 5700xt

**Comment by chrishilbert** [comment] 2022-01-15 03:12
I'm also having an issue where it won't start on HiveOS and terminators with errors over and over.  Won't start on my AMD only rig.

`successfully to authorize
00:00:00 [2022-01-14 21:51:24.786] Difficulty is 
set to 2.328200
00:00:00 [2022-01-14 21:51:24.787] GPU3 Starting 
generating ethash dag (Epoch: 466)
00:00:00 [2022-01-14 21:51:24.792] GPU4 Starting 
generating ethash dag (Epoch: 466)
00:00:00 [2022-01-14 21:51:24.792] GPU2 Starting 
generating ethash dag (Epoch: 466)
00:00:00 [2022-01-14 21:51:24.792] GPU0 Starting 
generating ethash dag (Epoch: 466)
00:00:00 [2022-01-14 21:51:24.792] GPU1 Starting 
generating ethash dag (Epoch: 466)
terminate called after throwing an instance of 'cl::BuildError'
  what():  clBuildProgram
00:00:00 [2022-01-14 21:51:37.693]                
                                                                 
00:00:00 [2022-01-14 21:51:37.845] OpenCL driver v
ersion: 318.0
00:00:00 [2022-01-14 21:51:37.864] Cuda driver ver`

**Comment by SirSchulz** [comment] 2022-01-15 23:44
Unfortunately, Teamblackminer does not work for me. Too bad for me

**Comment by frelon2max** [comment] 2022-01-16 16:42
> I'm also having an issue where it won't start on HiveOS and terminates with errors over and over. Won't start on my AMD only rig.
> 
> `00:00:00 [2022-01-14 21:51:38.204] GPU4 Starting generating ethash dag (Epoch: 466) 00:00:00 [2022-01-14 21:51:38.204] GPU3 Starting generating ethash dag (Epoch: 466) 00:00:00 [2022-01-14 21:51:38.204] GPU1 Starting generating ethash dag (Epoch: 466) 00:00:00 [2022-01-14 21:51:38.204] GPU0 Starting generating ethash dag (Epoch: 466) terminate called after throwing an instance of 'cl::BuildError' what(): clBuildProgram 00:00:00 [2022-01-14 21:51:51.130]
> 
> 00:00:00 [2022-01-14 21:51:51.280] OpenCL driver version: 318.0 00:00:00 [2022-01-14 21:51:51.300] Cuda driver version: 11.4 00:00:00 [2022-01-14 21:51:51.300] Cuda runtime API version: 11.4 00:00:00 [2022-01-14 21:51:51.300] 00:00:00 [2022-01-14 21:51:51.300] 00:00:00 [2022-01-14 21:51:51.300] 00:00:00 [2022-01-14 21:51:51.300] Welcome to Team Black Miner 1.39`

Same problem to me in HiveOS using the last available TBM version (1.39). Maybe a broken link to OpenCL libs. Any suggestion on how to solve?

**Comment by sp-hash** [comment] 2022-01-16 19:35
The build error is fixed in 1.40

**Closed by sp-hash** 2022-01-16 19:35 UTC
